// req: Request
export async function GET() {
  const products = [
    {
      id: 1,
      name: "grilled fish",
      image: "/assets/images/dish/GrilledFishWithVegetables-mix.png",
      rating: 4.5,
      price: 100,
      type: "non veg",
      category: "lunch",
      pieces: 2,
    },
    {
      id: 2,
      name: "salad pasts",
      image: "/assets/images/dish/SaladPasta-mix.png",
      rating: 4.0,
      price: 150,
      type: "veg",
      category: "breakfast",
      pieces: 4,
    },
    {
      id: 3,
      name: "shrimp",
      image: "/assets/images/dish/shrimp-nonVeg.png",
      rating: 4.8,
      price: 80,
      type: "mixed",
      category: "dinner",
      pieces: 1,
    },
    {
      id: 4,
      name: "Ceviche",
      image: "/assets/images/dish/Ceviche-nonVeg.png",
      rating: 4.7,
      price: 200,
      type: "non Veg",
      category: "lunch",
      pieces: 1,
    },
    {
      id: 5,
      name: "smoked salmon",
      image: "/assets/images/dish/SmokedSalmon-nonVeg.png",
      rating: 5,
      price: 225,
      type: "non veg",
      category: "lunch",
      pieces: 1,
    },
    {
      id: 6,
      name: "sushi sashimi",
      image: "/assets/images/dish/SushiSashimi-veg.png",
      rating: 5,
      price: 500,
      type: "veg",
      category: "breakfast",
      pieces: 1,
    },
    {
      id: 7,
      name: "smoked prawn",
      image: "/assets/images/dish/smoked-prawn.png",
      rating: 4.9,
      price: 150,
      type: "non veg",
      category: "lunch",
      pieces: 3,
    },
    {
      id: 8,
      name: "panner noodles",
      image: "/assets/images/dish/3.png",
      rating: 5,
      price: 70,
      type: "veg",
      category: "breakfast",
      pieces: 2,
    },
    {
      id: 9,
      name: "seafood pizza barbecue",
      image: "/assets/images/dish/SeafoodPizzaBarbecue-nonVeg.png",
      rating: 4.8,
      price: 270,
      type: "non veg",
      category: "lunch",
      pieces: 1,
    },
  ];

  return new Response(JSON.stringify(products), {
    status: 200,
    headers: { "Content-Type": "application/json" },
  });
}
